const CREATE_DOCUMENT_BEGIN = "CREATE_DOCUMENT_BEGIN"
const CREATE_DOCUMENT_SUCCESS = "CREATE_DOCUMENT_SUCCESS"
const CREATE_DOCUMENT_ERROR = "CREATE_DOCUMENT_ERROR"
const SET_DOC_MODE = "SET_DOC_MODE"
const SET_SELECTED_DOC = "SET_SELECTED_DOC"
const SET_SELECTED_MENU_ITEM = "SET_SELECTED_MENU_ITEM"

export { 
    CREATE_DOCUMENT_BEGIN, 
    CREATE_DOCUMENT_SUCCESS, 
    CREATE_DOCUMENT_ERROR,
    SET_DOC_MODE,
    SET_SELECTED_DOC,
    SET_SELECTED_MENU_ITEM
}